blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://discord.gg/refine
    about: If you have any questions or want to discuss something, then join our Discord server
